GET http://localhost:4000/todos/

###

POST http://localhost:4000/todos
Content-Type: application/json

{
  "task": "brush hair",
  "completed": "false"
}

###

DELETE http://localhost:4000/todos/46b77e24-96ce-403a-be08-e4559d950b58

###

PATCH http://localhost:4000/todos/173b834b-0331-4516-93d5-83e5321fc682
Content-Type: application/json

{
  "completed": "false"
}
# {
#   "task": "sing a song"
# }