GET http://localhost:4000/todos/

###

POST http://localhost:4000/todos
Content-Type: application/json

{
  "task": "brush hair",
  "completed": "false"
}

###

DELETE http://localhost:4000/todos/46b77e24-96ce-403a-be08-e4559d950b58

###

PATCH http://localhost:4000/todos/ae1d9ebc-28e4-4606-a05f-9addcf6a5919
Content-Type: application/json

# {
#   "completed": "true"
# }
{
  "task": "sing a song"
}