GET http://localhost:4000/todos/

###

POST http://localhost:4000/todos
Content-Type: application/json

{
  "task": "dance",
  "completed": "false"
}

###

DELETE http://localhost:4000/todos/08dfa68d-6c8d-42ca-8fae-633900bf36f8

###

PATCH http://localhost:4000/todos/1
Content-Type: application/json

{
  "completed": "true"
}